name: Trigger POST API

on:
  repository_dispatch:
    types: [trigger-post]

jobs:
  trigger-post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Trigger POST request
        run: |
          curl -X POST https://testgit.free.beeceptor.com \
          -H "Content-Type: application/json" \
          -d '{"api_test":"successful"}'
