name: Trigger POST API

on:
  workflow_dispatch:

jobs:
  trigger-post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Trigger POST request
        run: |
          curl -X POST https://api.example.com/endpoint \
          -H "Content-Type: application/json" \
          -d '{"key":"value"}'
